version: '3'
services:

  wize1:
    build:
      context: ./wizeNode
      args:
        app_port: 3000
        app_address: wize1
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize1
    environment:
      NODE_ID: 3000
      NODE_ADD: wize1
    ports:
      - "3000:3000"
      - "4000:4000"
#    links:
#      - wize2
#      - wize3
    networks:
      - front-tier
      - back-tier
    depends_on:
      - raft3-node

  wize2:
    build:
      context: ./wizeNode
      args:
        app_port: 3001
        app_address: wize2
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize2
    environment:
      NODE_ID: 3001
      NODE_ADD: wize2
    ports:
      - "3001:3000"
      - "4001:4000"
    links:
      - wize1:wizeNode-master
    networks:
      - front-tier
      - back-tier
    depends_on:
      - wize1

  wize3:
    build:
      context: ./wizeNode
      args:
        app_port: 3002
        app_address: wize3
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize3
    environment:
      NODE_ID: 3002
      NODE_ADD: wize3
    ports:
      - "3002:3000"
      - "4002:4000"
    links:
      - wize1:wizeNode-master
      - wize2:wizeNode-miner
    networks:
      - front-tier
      - back-tier
    depends_on:
      - wize1


  raft1-node:
    build:
      context: ./raft
      args:
        name: raft1
        app_address: wize1
    volumes:
      - ./raft/db/raft1:/go/src/wizeBlock/raft/db/raft1
    container_name: raft1-node
    environment:
      NODE_COMMAND: -id raft1-node -haddr raft1-node:11000 -raddr raft1-node:12000 ~/node
    ports:
      - "11001:11000"
      - "12001:12000"
#    links:
#      - wize1:wizeNode-master
#      - wize2:wizeNode-miner
    networks:
      - front-tier
      - raft-tier
#    depends_on:
#      - wize1

  raft2-node:
    build:
      context: ./raft
      args:
        name: raft2
        app_address: wize1
    volumes:
      - ./raft/db/raft2:/go/src/wizeBlock/raft/db/raft2
    container_name: raft2-node
    environment:
      NODE_COMMAND: -id raft2-node -haddr raft2-node:11000 -raddr raft2-node:12000 -join raft1-node:11000 ~/node
    ports:
      - "11002:11000"
      - "12002:12000"
    links:
      - raft1-node:raftNode-master
#      - wize2:wizeNode-miner
    networks:
      - front-tier
      - raft-tier
    depends_on:
      - raft1-node

  raft3-node:
    build:
      context: ./raft
      args:
        name: raft3
        app_address: wize1
    volumes:
      - ./raft/db/raft3:/go/src/wizeBlock/raft/db/raft3
    container_name: raft3-node
    environment:
      NODE_COMMAND: -id raft3-node -haddr raft3-node:11000 -raddr raft3-node:12000 -join raft1-node:11000 ~/node
    ports:
      - "11003:11000"
      - "12003:12000"
    links:
      - raft1-node:raftNode-master
      - raft2-node:raftNode-slave
    networks:
      - front-tier
      - raft-tier
    depends_on:
      - raft2-node

networks:
  front-tier:
  back-tier:
  raft-tier:

