version: '3'
services:

  wize1:
    build:
      context: ./wizeNode
      args:
        app_port: 3000
        app_address: wize1
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize1
    environment:
      NODE_ID: 3000
      NODE_ADD: wize1
    ports:
      - "3000:3000"
      - "4000:4000"
#    links:
#      - wize2
#      - wize3
    networks:
      - front-tier
      - back-tier

  wize2:
    build:
      context: ./wizeNode
      args:
        app_port: 3001
        app_address: wize2
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize2
    environment:
      NODE_ID: 3001
      NODE_ADD: wize2
    ports:
      - "3001:3000"
      - "4001:4000"
    links:
      - wize1:wizeNode-master
    networks:
      - front-tier
      - back-tier
    depends_on:
      - wize1

  wize3:
    build:
      context: ./wizeNode
      args:
        app_port: 3002
        app_address: wize3
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize3
    environment:
      NODE_ID: 3002
      NODE_ADD: wize3
    ports:
      - "3002:3000"
      - "4002:4000"
    links:
      - wize1:wizeNode-master
      - wize2:wizeNode-miner
    networks:
      - front-tier
      - back-tier
    depends_on:
      - wize1

networks:
  front-tier:
  back-tier:

