version: '3'
services:

  wize1:
    build:
      context: ./wizeNode
#      args:
#        app_port: 3000
#        app_address: wize1
    volumes:
      - ./wizeNode/files/initialnodes.json:/go/src/wizeBlock/wizeNode/files/initialnodes.json
      - ./wizeNode/files/db3000:/go/src/wizeBlock/wizeNode/files/db3000
      - ./wizeNode/files/wallet3000:/go/src/wizeBlock/wizeNode/files/wallet3000
    container_name: wize1
    environment:
      NODE_ID: 3000
      NODE_ADD: wize1
      PUBLIC_IP: ${PUBLIC_IP}
      USER_PRIVKEY: ${USER_PRIVKEY}
      USER_PUBKEY: ${USER_PUBKEY}
      USER_ADDRESS: ${USER_ADDRESS}
      PASSWORD: ${PASSWORD}
      SERVER_KEY: ${SERVER_KEY}
      DIGEST_NODE: ${DIGEST_NODE}
      MASTERNODE: wize1
      NODE_COMMAND: startnode
    ports:
      - "3000:3000"
      - "4000:4000"
#    links:
#      - wize2
#      - wize3
    networks:
      - front-tier
      - back-tier
    depends_on:
      - raft3-node
#    healthcheck:
#      test: ["CMD", "curl", "-f", "wize1:3000"]
#      interval: 10s
#      timeout: 10s
#      retries: 5


  raft1-node:
    build:
      context: ./raft
#      args:
#        name: raft1
#        app_address: wize1
    volumes:
      - ./raft/db/raft1:/go/src/wizeBlock/raft/db/raft1
    container_name: raft1-node
    environment:
      NODE_ID: ${NODE_ID}
      NODE_ADD: ${NODE_ADD}
      PUBLIC_IP: ${PUBLIC_IP}
      USER_PRIVKEY: ${USER_PRIVKEY}
      USER_PUBKEY: ${USER_PUBKEY}
      USER_ADDRESS: ${USER_ADDRESS}
      PASSWORD: ${PASSWORD}
      SERVER_KEY: ${SERVER_KEY}
      DIGEST_NODE: ${DIGEST_NODE}
      MASTERNODE: ${MASTERNODE}
      NODE_COMMAND: -id raft1-node -haddr raft1-node:11000 -raddr raft1-node:12000 ~/node
    ports:
      - "11001:11000"
      - "12001:12000"
#    links:
#      - wize1:wizeNode-master
#      - wize2:wizeNode-miner
    networks:
      - front-tier
      - raft-tier
#    depends_on:
#      - wize1



networks:
  front-tier:
  back-tier:
  raft-tier:

