version: '3'
services:

  wize1:
    build:
      context: ./wizeNode
      args:
        app_port: 3000
        app_address: wize1
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize1
    environment:
      NODE_ID: 3000
      NODE_ADD: wize1
    ports:
      - "3000:3000"
      - "4000:4000"
#    links:
#      - wize2
#      - wize3
    networks:
      - front-tier
      - back-tier

  wize2:
    build:
      context: ./wizeNode
      args:
        app_port: 3001
        app_address: wize2
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize2
    environment:
      NODE_ID: 3001
      NODE_ADD: wize2
    ports:
      - "3001:3000"
      - "4001:4000"
    links:
      - wize1:wizeNode-master
    networks:
      - front-tier
      - back-tier
    depends_on:
      - wize1

  wize3:
    build:
      context: ./wizeNode
      args:
        app_port: 3002
        app_address: wize3
    volumes:
      - ./wizeNode/files:/go/src/wizeBlock/wizeNode/files
    container_name: wize3
    environment:
      NODE_ID: 3002
      NODE_ADD: wize3
    ports:
      - "3002:3000"
      - "4002:4000"
    links:
      - wize1:wizeNode-master
      - wize2:wizeNode-miner
    networks:
      - front-tier
      - back-tier
    depends_on:
      - wize1


  raft1:
    build:
      context: ./fart
      args:
        app_port: 3000
        app_address: wize1
    volumes:
      - ./fart/db/raft1:/go/src/wizeBlock/fart/db/raft1
    container_name: raft1
    environment:
      NODE_ID: 3000
      NODE_ADD: wize1
    ports:
      - "11001:11000"
      - "12001:12000"
#    links:
#      - wize1:wizeNode-master
#      - wize2:wizeNode-miner
    networks:
      - front-tier
      - raft-tier
#    depends_on:
#      - wize1

  raft2:
    build:
      context: ./fart
      args:
        app_port: 3000
        app_address: wize1
    volumes:
      - ./fart/db/raft2:/go/src/wizeBlock/fart/db/raft2
    container_name: raft2
    environment:
      NODE_ID: 3000
      NODE_ADD: wize1
    ports:
      - "11002:11000"
      - "12002:12000"
    links:
      - raft1:raftNode-master
#      - wize2:wizeNode-miner
    networks:
      - front-tier
      - raft-tier
    depends_on:
      - raft1

  raft3:
    build:
      context: ./fart
      args:
        app_port: 3000
        app_address: wize1
    volumes:
      - ./fart/db/raft3:/go/src/wizeBlock/fart/db/raft3
    container_name: raft3
    environment:
      NODE_ID: 3000
      NODE_ADD: wize1
    ports:
      - "11003:11000"
      - "12003:12000"
    links:
      - raft1:raftNode-master
      - raft2:raftNode-slave
    networks:
      - front-tier
      - raft-tier
    depends_on:
      - raft1

networks:
  front-tier:
  back-tier:
  raft-tier:

