---
# =====================
# WEB SERVER SECTION
# =====================
- hosts: node

  tasks:

# INSTALL NODEJS, NPM, GIT
    - name: Adding the PPA for Node.js
      shell: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      args:
        warn: false

    - name: Install Node.js, npm
      apt: name=nodejs state=latest update_cache=yes

    - name: Install Git
      apt: pkg=git-core update_cache=yes

# INSTALL DOCKER CE
    - name: Add the GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      args:
        warn: false

    - name: Add repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Install Docker CE
      apt: name=docker-ce state=latest update_cache=yes

    - name: Install Docker Compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      args:
        warn: false

# PREPARE SSH KEY FOR REPOSITORY
    - name: Create SSH directory
      file:
        path: ~/.ssh
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: Copy SSH key
      copy:
        src: ssh/wize_node
        dest: ~/.ssh/wize_node
        owner: root
        group: root
        mode: 0600
    
    - name: Create SSH config file
      file:
        path: ~/.ssh/config
        state: touch
        owner: root
        group: root
        mode: 0644

    - name: Force key through config
      blockinfile:
        path: ~/.ssh/config
        block: |
          Host bitbucket
              HostName bitbucket.org
              IdentityFile ~/.ssh/wize_node

# CREATE DIRECTORIES FOR APPLICATION
    - name: Creates app directories
      file: 
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      with_items:
        - /home/wizeblock
        - /home/wizefs

# CLONING REPOSITORIES
    - name: Clone wizeBlock repository
      git:
        repo: git@bitbucket.org:udt/wizeblock.git
        key_file: ~/.ssh/wize_node
        dest: /home/wizeblock
        force: true

    - name: Clone wizeFS repository
      git:
        repo: git@bitbucket.org:udt/wizefs.git
        key_file: ~/.ssh/wize_node
        dest: /home/wizefs
        force: true

# RUN APPLICATION
#   - name: Run wizeBlock
#     shell: cd /home/wizeblock && bash ./start_cluster.sh
#
#   - name: Run wizeFS
#     shell: cd /home/wizefs && bash ./start.sh